# Generated by Django 4.0.4 on 2022-05-10 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_category_name_alter_listing_date_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_made',
            field=models.DateField(default=datetime.datetime(2022, 5, 10, 15, 32, 21, 153042)),
        ),
    ]
