# Generated by Django 4.0.4 on 2022-05-10 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_category_alter_listing_date_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_made',
            field=models.DateField(default=datetime.datetime(2022, 5, 10, 15, 42, 48, 822810)),
        ),
    ]
