# Generated by Django 4.0.4 on 2022-05-10 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_category_alter_listing_date_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_made',
            field=models.DateField(default=datetime.date(2022, 5, 10)),
        ),
    ]
