# Generated by Django 4.0.4 on 2022-05-11 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(db_constraint=False, default='Other', on_delete=django.db.models.deletion.CASCADE, related_name='category_listings', to='auctions.category', to_field='name'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_made',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
