# Generated by Django 4.0.4 on 2022-05-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_category_alter_listing_date_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image_url',
        ),
        migrations.AddField(
            model_name='listing',
            name='upload_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
