# Generated by Django 4.0.4 on 2022-05-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_category_name_alter_listing_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='upload_image',
            field=models.ImageField(blank=True, upload_to='media/media'),
        ),
    ]
